In [11]:
import numpy as np
from sympy import preview

scalar = 3
print(f'Scalar Value:\n{scalar}\n')

vector = np.array([1,2,3,4,5], dtype=np.int)
print(f'Vector Value:\n{vector}\n')

matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16],
    [17, 18, 19, 20],
])
print(f'Matrix Value:\n{matrix}\n')

tensor = np.array([
    np.array(list(range(1, 21))).reshape((5,4)), 
    np.array(list(range(21, 41))).reshape((5,4)),
    np.array(list(range(41, 61))).reshape((5,4)),
    ])

    [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]
  [17 18 19 20]]

 [[21 22 23 24]
  [25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]
  [37 38 39 40]]

 [[41 42 43 44]
  [45 46 47 48]
  [49 50 51 52]
  [53 54 55 56]
  [57 58 59 60]]]
print(f'Matrix Value:\n{tensor}\n')

IndentationError: unexpected indent (<ipython-input-11-4c9eca63ff6a>, line 25)