In [4]:
import numpy as np


scalar = 3
print(f'Scalar Value:\n{scalar}\n')

vector = np.array([1,2,3,4,5], dtype=np.int)
print(f'Vector Value:\n{vector}\n')

matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16],
    [17, 18, 19, 20],
])
print(f'Matrix Value:\n{matrix}\n')

tensor = np.concatenate([np.array(list(range(1, 21))).reshape((5,4)), np.array(list(range(21, 41))).reshape((5,4)))]
print(f'Matrix Value:\n{matrix}\n')

Scalar Value:
3

Vector Value:
[1 2 3 4 5]

Matrix Value:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]

